[workspace]
members = [
    "crates/core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Hellas AI <team@hellas.ai>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/hellas-ai/gate"
keywords = ["p2p", "llm", "inference", "encryption", "gateway"]
categories = ["network-programming", "cryptography"]

[workspace.dependencies]
# Will add dependencies as needed

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"