[workspace]
resolver = "2"
members = ["src-tauri"]
default-members = ["src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Hellas AI <team@hellas.ai>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/hellas-ai/gate"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"
