[[proxy]]
rewrite = "/api/"
backend = "http://localhost:31145/"

[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "./style.css", "-o", "./tailwind.output.css", "--minify"]

[serve]
addresses = ["127.0.0.1"]
port = 8082
open = false