[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "post_build"  
command = "sh"
command_arguments = ["-c", "pwd && cp -rv ../../../fixtures/data/cassettes"]

[serve]
port = 8081
open = false

[watch]
watch = ["../../src", "main.rs", "index.html"]