[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/nix/store/pqwiwgf6vsqa6gwslam239zjdsc82293-mold-2.40.1/bin/mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"  
rustflags = ["-C", "link-arg=-fuse-ld=/nix/store/pqwiwgf6vsqa6gwslam239zjdsc82293-mold-2.40.1/bin/mold"]
