[package]
name = "hellas-gate-daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Gate daemon for P2P AI inference network"

[dependencies]
# Workspace dependencies
hellas-gate-core = { path = "../core" }
hellas-gate-p2p = { path = "../p2p" }

tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "timeout"] }
hyper = "1.0"

# Configuration
config = "0.14"
serde_json = "1.0"
serde_yaml = "0.9"

# HTTP client for upstream providers
reqwest = { version = "0.11", features = ["json", "stream"] }


# System utilities
dirs = "5.0"

[dev-dependencies]
test-log = "0.2"

[features]
default = []
