[[proxy]]
rewrite = "/auth/"
backend = "http://localhost:3000/auth/"

[[proxy]]
rewrite = "/health"
backend = "http://localhost:3000/health"

[[proxy]]
rewrite = "/v1/"
backend = "http://localhost:3000/v1/"

[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "./style.css", "-o", "./tailwind.output.css", "--minify"]

[serve]
addresses = ["127.0.0.1"]
port = 8081
open = false