name: CI

on:
  push:
    branches: [ master, grw/feat/nix-ci ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    
    - uses: DeterminateSystems/nix-installer-action@main
    
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Check flake
      run: nix flake check
    
    - name: Build packages
      run: |
        nix build .#gate-daemon
        nix build .#gate-tlsforward
    
    - name: Run tests
      run: nix build .#checks.x86_64-linux.test
      if: runner.os == 'Linux'
    
    - name: Run tests (macOS)
      run: nix build .#checks.x86_64-darwin.test
      if: runner.os == 'macOS'