name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mkroening/rust-toolchain-toml@main
    - uses: Swatinem/rust-cache@v2
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    
    - name: Build
      run: cargo build --all-features
    
    - name: Test
      run: cargo test --all-features
  
  gui-build:
    name: GUI Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
    - uses: actions/checkout@v4
    
    - uses: DeterminateSystems/nix-installer-action@main
    
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Build GUI with Nix
      run: |
        nix develop --command make gui-build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gate-gui-${{ matrix.target }}
        path: |
          crates/gui/target/release/bundle/dmg/*.dmg
          crates/gui/target/release/bundle/macos/*.app
          crates/gui/target/release/bundle/deb/*.deb
          crates/gui/target/release/bundle/appimage/*.AppImage
          crates/gui/target/release/bundle/msi/*.msi
        if-no-files-found: warn
