name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mkroening/rust-toolchain-toml@main
    - uses: Swatinem/rust-cache@v2
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    
    - name: Build
      run: cargo build --all-features
    
    - name: Test
      run: cargo test --all-features
  
  gui-build:
    name: GUI Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
    - uses: actions/checkout@v4
    
    # Install Rust toolchain
    - uses: mkroening/rust-toolchain-toml@main
    - uses: Swatinem/rust-cache@v2
    
    # Add WASM target
    - name: Add WASM target
      run: rustup target add wasm32-unknown-unknown
    
    # Cache cargo-installed tools
    - name: Cache cargo tools
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-tools-trunk-tauri-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-tools-trunk-tauri-
          ${{ runner.os }}-cargo-tools-
    
    # Install build tools
    - name: Install build tools
      run: |
        # Check if trunk is already installed
        if ! command -v trunk &> /dev/null; then
          echo "Installing trunk..."
          cargo install trunk --locked
        else
          echo "trunk is already installed"
        fi
        
        # Check if tauri is already installed
        if ! command -v cargo-tauri &> /dev/null; then
          echo "Installing tauri-cli..."
          cargo install tauri-cli@2.0.0 --locked
        else
          echo "tauri-cli is already installed"
        fi
    
    # Install Node.js for tailwindcss
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install tailwindcss
      run: |
        npm install -g tailwindcss
        # Create symlink to ensure tailwindcss is in PATH
        sudo ln -sf $(npm config get prefix)/bin/tailwindcss /usr/local/bin/tailwindcss
        # Verify it's accessible (use full path to avoid shell cache issues)
        /usr/local/bin/tailwindcss --version
    
    # Linux-specific dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev
    
    # Build frontends and GUI
    - name: Build GUI
      env:
        RUSTFLAGS: '--cfg getrandom_backend="wasm_js"'
      run: |
        # Build WASM frontends first
        cd crates/frontend-daemon && trunk build --release
        cd ../frontend-tauri && trunk build --release
        
        # Build Tauri app
        cd ../gui && cargo tauri build
    
    - name: Find and prepare artifacts
      run: |
        mkdir -p artifacts
        
        # Tauri outputs to crates/gui/target/release/bundle
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          # macOS: Look for DMG and app bundles
          if [[ -d "crates/gui/target/release/bundle" ]]; then
            echo "Found macOS bundles"
            cp -r crates/gui/target/release/bundle/dmg/*.dmg artifacts/ 2>/dev/null || true
            cp -r crates/gui/target/release/bundle/macos/*.app artifacts/ 2>/dev/null || true
          fi
        elif [[ "${{ runner.os }}" == "Linux" ]]; then
          # Linux: Look for deb and AppImage files
          if [[ -d "crates/gui/target/release/bundle" ]]; then
            echo "Found Linux bundles"
            cp -r crates/gui/target/release/bundle/deb/*.deb artifacts/ 2>/dev/null || true
            cp -r crates/gui/target/release/bundle/appimage/*.AppImage artifacts/ 2>/dev/null || true
          fi
        fi
        
        # List what we found
        echo "Artifacts found:"
        ls -la artifacts/ || echo "No artifacts directory"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gate-gui-${{ matrix.target }}
        path: artifacts/*
        if-no-files-found: warn
