name: CI

on:
  push:
    branches: [ master, grw/feat/nix-ci ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    
    - uses: DeterminateSystems/nix-installer-action@main
    
    - uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Detect system
      id: system
      run: |
        system=$(nix eval --impure --raw --expr 'builtins.currentSystem')
        echo "System: $system"
        echo "system=$system" >> $GITHUB_OUTPUT
    
    - name: Check flake
      run: nix flake check
    
    - name: Build packages
      run: |
        nix build .#gate-daemon
        nix build .#gate-tlsforward
    
    - name: Run tests
      run: |
        echo "Running tests for system: ${{ steps.system.outputs.system }}"
        nix build .#checks.${{ steps.system.outputs.system }}.test
    
    - name: Run clippy
      run: nix build .#checks.${{ steps.system.outputs.system }}.clippy
    
    - name: Check formatting
      run: nix build .#checks.${{ steps.system.outputs.system }}.fmt